spring:
  elasticsearch:
    uris: http://localhost:9200
#    enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/yangpei?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    initial-size: 5
    max-active: 15
    max-wait: 60000

  druid:
    initial-size: 5
    max-active: 15
    max-wait: 60000
    min-idle: 5

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: sk-ae5952db2cab473d863d43a59b41a493
        type: in-memory
        max-messages: 20
        max-tokens: 1024
        enable-search: false
        tool-choice: auto

mlqs:
  agent:
    # 代理超时时间，单位秒
    timeout: 300
  log:
    # debug输出
    debug: true
    # 计划报告输出
    report: true
    # 报告的时间表达式
    report-cron: 0 0/1 * * * ?
  embedding:
    url: http://localhost:5000/convert
  rerank:
    url: http://localhost:5001/rerank


